package com.erfangholami.androidsolidservices.shared.vocab

/**
 * Schema.org vocabulary constants.
 * https://schema.org/
 * Broadly used in Solid apps for typed data (media, events, products, etc.).
 */
public object Schema {
    public const val NAMESPACE: String = "https://schema.org/"

    public const val THING: String = "${NAMESPACE}Thing"
    public const val CREATIVE_WORK: String = "${NAMESPACE}CreativeWork"
    public const val MEDIA_OBJECT: String = "${NAMESPACE}MediaObject"
    public const val MOVIE: String = "${NAMESPACE}Movie"
    public const val MUSIC_RECORDING: String = "${NAMESPACE}MusicRecording"
    public const val BOOK: String = "${NAMESPACE}Book"
    public const val ARTICLE: String = "${NAMESPACE}Article"
    public const val BLOG_POSTING: String = "${NAMESPACE}BlogPosting"
    public const val EVENT: String = "${NAMESPACE}Event"
    public const val PERSON: String = "${NAMESPACE}Person"
    public const val ORGANIZATION: String = "${NAMESPACE}Organization"
    public const val PLACE: String = "${NAMESPACE}Place"
    public const val PRODUCT: String = "${NAMESPACE}Product"
    public const val OFFER: String = "${NAMESPACE}Offer"

    public const val RESERVATION: String = "${NAMESPACE}Reservation"
    public const val EVENT_RESERVATION: String = "${NAMESPACE}EventReservation"
    public const val FLIGHT_RESERVATION: String = "${NAMESPACE}FlightReservation"
    public const val TRAIN_RESERVATION: String = "${NAMESPACE}TrainReservation"
    public const val BUS_RESERVATION: String = "${NAMESPACE}BusReservation"
    public const val BOAT_RESERVATION: String = "${NAMESPACE}BoatReservation"
    public const val LODGING_RESERVATION: String = "${NAMESPACE}LodgingReservation"

    public const val TRIP: String = "${NAMESPACE}Trip"
    public const val FLIGHT: String = "${NAMESPACE}Flight"
    public const val TRAIN_TRIP: String = "${NAMESPACE}TrainTrip"
    public const val BUS_TRIP: String = "${NAMESPACE}BusTrip"
    public const val BOAT_TRIP: String = "${NAMESPACE}BoatTrip"
    public const val AIRPORT: String = "${NAMESPACE}Airport"
    public const val TRAIN_STATION: String = "${NAMESPACE}TrainStation"
    public const val BUS_STOP: String = "${NAMESPACE}BusStop"
    public const val BOAT_TERMINAL: String = "${NAMESPACE}BoatTerminal"
    public const val LODGING_BUSINESS: String = "${NAMESPACE}LodgingBusiness"

    public const val MUSIC_EVENT: String = "${NAMESPACE}MusicEvent"
    public const val SPORTS_EVENT: String = "${NAMESPACE}SportsEvent"
    public const val SCREENING_EVENT: String = "${NAMESPACE}ScreeningEvent"
    public const val THEATER_EVENT: String = "${NAMESPACE}TheaterEvent"
    public const val FESTIVAL: String = "${NAMESPACE}Festival"
    public const val SPORTS_TEAM: String = "${NAMESPACE}SportsTeam"
    public const val AIRLINE: String = "${NAMESPACE}Airline"
    public const val PROGRAM_MEMBERSHIP: String = "${NAMESPACE}ProgramMembership"
    public const val POSTAL_ADDRESS: String = "${NAMESPACE}PostalAddress"
    public const val GEO_COORDINATES: String = "${NAMESPACE}GeoCoordinates"

    public const val RESERVATION_CONFIRMED: String = "${NAMESPACE}ReservationConfirmed"
    public const val RESERVATION_PENDING: String = "${NAMESPACE}ReservationPending"
    public const val RESERVATION_HOLD: String = "${NAMESPACE}ReservationHold"
    public const val RESERVATION_CANCELLED: String = "${NAMESPACE}ReservationCancelled"
    public const val EVENT_SCHEDULED: String = "${NAMESPACE}EventScheduled"
    public const val EVENT_RESCHEDULED: String = "${NAMESPACE}EventRescheduled"
    public const val EVENT_POSTPONED: String = "${NAMESPACE}EventPostponed"
    public const val EVENT_CANCELLED: String = "${NAMESPACE}EventCancelled"
    public const val EVENT_MOVED_ONLINE: String = "${NAMESPACE}EventMovedOnline"
    public const val GROUP_BOARDING_POLICY: String = "${NAMESPACE}GroupBoardingPolicy"
    public const val ZONE_BOARDING_POLICY: String = "${NAMESPACE}ZoneBoardingPolicy"

    public const val RESERVED_TICKET: String = "${NAMESPACE}reservedTicket"
    public const val RESERVATION_FOR: String = "${NAMESPACE}reservationFor"
    public const val RESERVATION_ID: String = "${NAMESPACE}reservationId"
    public const val RESERVATION_STATUS: String = "${NAMESPACE}reservationStatus"
    public const val BOOKING_TIME: String = "${NAMESPACE}bookingTime"
    public const val MODIFIED_TIME: String = "${NAMESPACE}modifiedTime"
    public const val BROKER: String = "${NAMESPACE}broker"
    public const val PROGRAM_MEMBERSHIP_USED: String = "${NAMESPACE}programMembershipUsed"
    public const val BOARDING_GROUP: String = "${NAMESPACE}boardingGroup"
    public const val PASSENGER_SEQUENCE_NUMBER: String = "${NAMESPACE}passengerSequenceNumber"
    public const val PASSENGER_PRIORITY_STATUS: String = "${NAMESPACE}passengerPriorityStatus"
    public const val SECURITY_SCREENING: String = "${NAMESPACE}securityScreening"
    public const val CHECKIN_TIME: String = "${NAMESPACE}checkinTime"
    public const val CHECKOUT_TIME: String = "${NAMESPACE}checkoutTime"
    public const val NUM_ADULTS: String = "${NAMESPACE}numAdults"
    public const val NUM_CHILDREN: String = "${NAMESPACE}numChildren"

    public const val DEPARTURE_TIME: String = "${NAMESPACE}departureTime"
    public const val ARRIVAL_TIME: String = "${NAMESPACE}arrivalTime"
    public const val PROVIDER: String = "${NAMESPACE}provider"
    public const val FLIGHT_NUMBER: String = "${NAMESPACE}flightNumber"
    public const val DEPARTURE_AIRPORT: String = "${NAMESPACE}departureAirport"
    public const val ARRIVAL_AIRPORT: String = "${NAMESPACE}arrivalAirport"
    public const val DEPARTURE_GATE: String = "${NAMESPACE}departureGate"
    public const val ARRIVAL_GATE: String = "${NAMESPACE}arrivalGate"
    public const val DEPARTURE_TERMINAL: String = "${NAMESPACE}departureTerminal"
    public const val ARRIVAL_TERMINAL: String = "${NAMESPACE}arrivalTerminal"
    public const val AIRCRAFT: String = "${NAMESPACE}aircraft"
    public const val BOARDING_POLICY: String = "${NAMESPACE}boardingPolicy"
    public const val TRAIN_NUMBER: String = "${NAMESPACE}trainNumber"
    public const val TRAIN_NAME: String = "${NAMESPACE}trainName"
    public const val DEPARTURE_STATION: String = "${NAMESPACE}departureStation"
    public const val ARRIVAL_STATION: String = "${NAMESPACE}arrivalStation"
    public const val DEPARTURE_PLATFORM: String = "${NAMESPACE}departurePlatform"
    public const val ARRIVAL_PLATFORM: String = "${NAMESPACE}arrivalPlatform"
    public const val BUS_NUMBER: String = "${NAMESPACE}busNumber"
    public const val BUS_NAME: String = "${NAMESPACE}busName"
    public const val DEPARTURE_BUS_STOP: String = "${NAMESPACE}departureBusStop"
    public const val ARRIVAL_BUS_STOP: String = "${NAMESPACE}arrivalBusStop"
    public const val DEPARTURE_BOAT_TERMINAL: String = "${NAMESPACE}departureBoatTerminal"
    public const val ARRIVAL_BOAT_TERMINAL: String = "${NAMESPACE}arrivalBoatTerminal"
    public const val IATA_CODE: String = "${NAMESPACE}iataCode"

    public const val DOOR_TIME: String = "${NAMESPACE}doorTime"
    public const val EVENT_STATUS: String = "${NAMESPACE}eventStatus"
    public const val PREVIOUS_START_DATE: String = "${NAMESPACE}previousStartDate"
    public const val PERFORMER: String = "${NAMESPACE}performer"
    public const val HOME_TEAM: String = "${NAMESPACE}homeTeam"
    public const val AWAY_TEAM: String = "${NAMESPACE}awayTeam"
    public const val WORK_PRESENTED: String = "${NAMESPACE}workPresented"

    public const val GEO: String = "${NAMESPACE}geo"
    public const val LATITUDE: String = "${NAMESPACE}latitude"
    public const val LONGITUDE: String = "${NAMESPACE}longitude"

    /** The elevation of a location, in metres (`schema:elevation`). */
    public const val ELEVATION: String = "${NAMESPACE}elevation"
    public const val LOGO: String = "${NAMESPACE}logo"
    public const val STREET_ADDRESS: String = "${NAMESPACE}streetAddress"
    public const val ADDRESS_LOCALITY: String = "${NAMESPACE}addressLocality"
    public const val ADDRESS_REGION: String = "${NAMESPACE}addressRegion"
    public const val POSTAL_CODE: String = "${NAMESPACE}postalCode"
    public const val ADDRESS_COUNTRY: String = "${NAMESPACE}addressCountry"

    public const val SEATING_TYPE: String = "${NAMESPACE}seatingType"
    public const val PROGRAM_NAME: String = "${NAMESPACE}programName"
    public const val MEMBERSHIP_NUMBER: String = "${NAMESPACE}membershipNumber"
    public const val HOSTING_ORGANIZATION: String = "${NAMESPACE}hostingOrganization"
    public const val ADDITIONAL_NAME: String = "${NAMESPACE}additionalName"
    public const val HONORIFIC_PREFIX: String = "${NAMESPACE}honorificPrefix"
    public const val HONORIFIC_SUFFIX: String = "${NAMESPACE}honorificSuffix"

    public const val NAME: String = "${NAMESPACE}name"
    public const val DESCRIPTION: String = "${NAMESPACE}description"
    public const val IMAGE: String = "${NAMESPACE}image"
    public const val URL: String = "${NAMESPACE}url"
    public const val IDENTIFIER: String = "${NAMESPACE}identifier"
    public const val SAME_AS: String = "${NAMESPACE}sameAs"
    public const val ADDITIONAL_TYPE: String = "${NAMESPACE}additionalType"

    public const val DATE_CREATED: String = "${NAMESPACE}dateCreated"
    public const val DATE_MODIFIED: String = "${NAMESPACE}dateModified"
    public const val DATE_PUBLISHED: String = "${NAMESPACE}datePublished"
    public const val AUTHOR: String = "${NAMESPACE}author"
    public const val CREATOR: String = "${NAMESPACE}creator"
    public const val PUBLISHER: String = "${NAMESPACE}publisher"
    public const val GENRE: String = "${NAMESPACE}genre"
    public const val KEYWORDS: String = "${NAMESPACE}keywords"
    public const val CONTENT_URL: String = "${NAMESPACE}contentUrl"
    public const val ENCODING_FORMAT: String = "${NAMESPACE}encodingFormat"
    public const val DURATION: String = "${NAMESPACE}duration"
    public const val IN_LANGUAGE: String = "${NAMESPACE}inLanguage"
    public const val THUMBNAIL_URL: String = "${NAMESPACE}thumbnailUrl"
    public const val LICENSE: String = "${NAMESPACE}license"

    public const val GIVEN_NAME: String = "${NAMESPACE}givenName"
    public const val FAMILY_NAME: String = "${NAMESPACE}familyName"
    public const val EMAIL: String = "${NAMESPACE}email"
    public const val TELEPHONE: String = "${NAMESPACE}telephone"
    public const val ADDRESS: String = "${NAMESPACE}address"
    public const val MEMBER_OF: String = "${NAMESPACE}memberOf"
    public const val KNOWS: String = "${NAMESPACE}knows"
    public const val BIRTH_DATE: String = "${NAMESPACE}birthDate"

    public const val START_DATE: String = "${NAMESPACE}startDate"
    public const val END_DATE: String = "${NAMESPACE}endDate"
    public const val LOCATION: String = "${NAMESPACE}location"
    public const val ORGANIZER: String = "${NAMESPACE}organizer"
    public const val ATTENDEE: String = "${NAMESPACE}attendee"

    public const val TICKET: String = "${NAMESPACE}Ticket"
    public const val SEAT: String = "${NAMESPACE}Seat"

    public const val TICKET_NUMBER: String = "${NAMESPACE}ticketNumber"

    /** The opaque token/payload encoded in the ticket's barcode. */
    public const val TICKET_TOKEN: String = "${NAMESPACE}ticketToken"
    public const val ISSUED_BY: String = "${NAMESPACE}issuedBy"
    public const val UNDER_NAME: String = "${NAMESPACE}underName"
    public const val TICKETED_SEAT: String = "${NAMESPACE}ticketedSeat"
    public const val SEAT_NUMBER: String = "${NAMESPACE}seatNumber"
    public const val SEAT_ROW: String = "${NAMESPACE}seatRow"
    public const val SEAT_SECTION: String = "${NAMESPACE}seatSection"
    public const val TOTAL_PRICE: String = "${NAMESPACE}totalPrice"
    public const val PRICE_CURRENCY: String = "${NAMESPACE}priceCurrency"
    public const val DATE_ISSUED: String = "${NAMESPACE}dateIssued"
    public const val VALID_FROM: String = "${NAMESPACE}validFrom"
    public const val VALID_THROUGH: String = "${NAMESPACE}validThrough"
}
